import { SalesRecord } from '../types';

export const defaultSalesData: SalesRecord[] = [
  {
    date: '2026-06-01',
    revenue: 12500,
    totalRevenue: 13500,
    discount: 1000,
    netRevenue: 11500,
    quantity: 1,
    gender: '여성',
    age: '20대',
    channel: '자사앱(잇츠)',
    store: '롯데리아 소공점',
    premium: 'VIP',
    region: '서울',
    category: '버거류',
    productName: '한우불고기버거 세트',
    receiptNo: 'R00189',
    customerId: 'cust_901'
  },
  {
    date: '2026-06-01',
    revenue: 9800,
    totalRevenue: 9800,
    discount: 0,
    netRevenue: 9800,
    quantity: 2,
    gender: '남성',
    age: '30대',
    channel: '배달의민족',
    store: '롯데리아 소공점',
    premium: '일반',
    region: '경기',
    category: '버거류',
    productName: '데리버거 단품',
    receiptNo: 'R00190',
    customerId: 'cust_304'
  },
  {
    date: '2026-06-02',
    revenue: 15400,
    totalRevenue: 17400,
    discount: 2000,
    netRevenue: 14000,
    quantity: 3,
    gender: '남성',
    age: '20대',
    channel: '쿠팡이츠',
    store: '크리스피크림 잠실점',
    premium: 'VVIP',
    region: '서울',
    category: '디저트/도넛',
    productName: '오리지널 글레이즈드 하프더즌',
    receiptNo: 'R00191',
    customerId: 'cust_502'
  },
  {
    date: '2026-06-02',
    revenue: 5500,
    totalRevenue: 5500,
    discount: 0,
    netRevenue: 5500,
    quantity: 1,
    gender: '여성',
    age: '40대',
    channel: '매장키오스크',
    store: '엔제리너스 명동점',
    premium: '일반',
    region: '인천',
    category: '커피류',
    productName: '아메리카노 L',
    receiptNo: 'R00192',
    customerId: 'cust_784'
  },
  {
    date: '2026-06-03',
    revenue: 23600,
    totalRevenue: 25600,
    discount: 2000,
    netRevenue: 21600,
    quantity: 2,
    gender: '여성',
    age: '30대',
    channel: '자사앱(잇츠)',
    store: '롯데리아 강남역점',
    premium: 'VIP',
    region: '서울',
    category: '버거류',
    productName: '새우버거 더블세트',
    receiptNo: 'R00193',
    customerId: 'cust_112'
  },
  {
    date: '2026-06-03',
    revenue: 6800,
    totalRevenue: 6800,
    discount: 0,
    netRevenue: 6800,
    quantity: 1,
    gender: '남성',
    age: '50대 이상',
    channel: '드라이브스루',
    store: '롯데리아 강남역점',
    premium: '일반',
    region: '경기',
    category: '버거류',
    productName: '불고기버거 단품',
    receiptNo: 'R00194',
    customerId: 'cust_498'
  },
  {
    date: '2026-06-04',
    revenue: 12000,
    totalRevenue: 13000,
    discount: 1000,
    netRevenue: 11000,
    quantity: 2,
    gender: '여성',
    age: '20대',
    channel: '매장키오스크',
    store: '엔제리너스 건대점',
    premium: '일반',
    region: '서울',
    category: '커피류',
    productName: '카페라떼 & 치즈케이크 세트',
    receiptNo: 'R00195',
    customerId: 'cust_220'
  },
  {
    date: '2026-06-04',
    revenue: 8500,
    totalRevenue: 8500,
    discount: 0,
    netRevenue: 8500,
    quantity: 1,
    gender: '남성',
    age: '20대',
    channel: '배달의민족',
    store: '크리스피크림 홍대점',
    premium: 'VIP',
    region: '경기',
    category: '디저트/도넛',
    productName: '어쏘티드 도넛 박스',
    receiptNo: 'R00196',
    customerId: 'cust_105'
  },
  {
    date: '2026-06-05',
    revenue: 35000,
    totalRevenue: 40000,
    discount: 5000,
    netRevenue: 31000,
    quantity: 4,
    gender: '여성',
    age: '30대',
    channel: '자사앱(잇츠)',
    store: '롯데리아 소공점',
    premium: 'VVIP',
    region: '서울',
    category: '버거류',
    productName: '패밀리 디럭스 팩 (리아불고기/새우)',
    receiptNo: 'R00197',
    customerId: 'cust_009'
  },
  {
    date: '2026-06-05',
    revenue: 6200,
    totalRevenue: 6200,
    discount: 0,
    netRevenue: 6200,
    quantity: 1,
    gender: '남성',
    age: '40대',
    channel: '매장키오스크',
    store: '엔제리너스 명동점',
    premium: '일반',
    region: '서울',
    category: '커피류',
    productName: '콜드브루 아인슈페너',
    receiptNo: 'R00198',
    customerId: 'cust_512'
  },
  {
    date: '2026-06-06',
    revenue: 18500,
    totalRevenue: 18500,
    discount: 0,
    netRevenue: 18500,
    quantity: 2,
    gender: '여성',
    age: '20대',
    channel: '쿠팡이츠',
    store: '크리스피크림 잠실점',
    premium: 'VIP',
    region: '경기',
    category: '디저트/도넛',
    productName: '초코 블라썸 도넛 더즌',
    receiptNo: 'R00199',
    customerId: 'cust_601'
  },
  {
    date: '2026-06-06',
    revenue: 7500,
    totalRevenue: 8500,
    discount: 1000,
    netRevenue: 6500,
    quantity: 1,
    gender: '남성',
    age: '30대',
    channel: '드라이브스루',
    store: '롯데리아 강남역점',
    premium: '일반',
    region: '인천',
    category: '음료',
    productName: '밀크쉐이크 & 포테이토 라지',
    receiptNo: 'R00200',
    customerId: 'cust_777'
  },
  {
    date: '2026-06-07',
    revenue: 11000,
    totalRevenue: 11000,
    discount: 0,
    netRevenue: 11000,
    quantity: 1,
    gender: '여성',
    age: '50대 이상',
    channel: '매장키오스크',
    store: '엔제리너스 건대점',
    premium: '일반',
    region: '서울',
    category: '커피류',
    productName: '바닐라 딜라이트 ICE & 쿠키',
    receiptNo: 'R00201',
    customerId: 'cust_803'
  },
  {
    date: '2026-06-07',
    revenue: 29000,
    totalRevenue: 32000,
    discount: 3000,
    netRevenue: 26000,
    quantity: 3,
    gender: '남성',
    age: '40대',
    channel: '배달의민족',
    store: '롯데리아 소공점',
    premium: 'VIP',
    region: '서울',
    category: '버거류',
    productName: '한우불고기 2인 세트',
    receiptNo: 'R00202',
    customerId: 'cust_554'
  },
  {
    date: '2026-06-08',
    revenue: 4800,
    totalRevenue: 4800,
    discount: 0,
    netRevenue: 4800,
    quantity: 1,
    gender: '여성',
    age: '20대',
    channel: '매장키오스크',
    store: '엔제리너스 명동점',
    premium: '일반',
    region: '서울',
    category: '음료',
    productName: '상큼 레몬에이드 R',
    receiptNo: 'R00203',
    customerId: 'cust_412'
  },
  {
    date: '2026-06-08',
    revenue: 13500,
    totalRevenue: 15000,
    discount: 1500,
    netRevenue: 12000,
    quantity: 1,
    gender: '남성',
    age: '30대',
    channel: '자사앱(잇츠)',
    store: '롯데리아 강남역점',
    premium: 'VVIP',
    region: '부산',
    category: '버거류',
    productName: '더블치즈No.5 스페셜 팩',
    receiptNo: 'R00204',
    customerId: 'cust_999'
  },
  {
    date: '2026-06-09',
    revenue: 17200,
    totalRevenue: 19200,
    discount: 2000,
    netRevenue: 15200,
    quantity: 2,
    gender: '여성',
    age: '30대',
    channel: '쿠팡이츠',
    store: '크리스피크림 홍대점',
    premium: 'VIP',
    region: '경기',
    category: '디저트/도넛',
    productName: '시그니처 하프더즌 기프트팩',
    receiptNo: 'R00205',
    customerId: 'cust_331'
  },
  {
    date: '2026-06-09',
    revenue: 5000,
    totalRevenue: 5000,
    discount: 0,
    netRevenue: 5000,
    quantity: 1,
    gender: '남성',
    age: '20대',
    channel: '매장키오스크',
    store: '엔제리너스 건대점',
    premium: '일반',
    region: '서울',
    category: '커피류',
    productName: '아메리카노 L',
    receiptNo: 'R00206',
    customerId: 'cust_205'
  },
  {
    date: '2026-06-10',
    revenue: 21000,
    totalRevenue: 24000,
    discount: 3000,
    netRevenue: 18000,
    quantity: 3,
    gender: '여성',
    age: '40대',
    channel: '자사앱(잇츠)',
    store: '롯데리아 소공점',
    premium: 'VVIP',
    region: '서울',
    category: '버거류',
    productName: '새우버거 3패키지 패밀리팩',
    receiptNo: 'R00207',
    customerId: 'cust_011'
  },
  {
    date: '2026-06-10',
    revenue: 9500,
    totalRevenue: 9500,
    discount: 0,
    netRevenue: 9500,
    quantity: 1,
    gender: '남성',
    age: '30대',
    channel: '배달의민족',
    store: '엔제리너스 명동점',
    premium: 'VIP',
    region: '경기',
    category: '커피류',
    productName: '카푸치노 특대 & 브레드',
    receiptNo: 'R00208',
    customerId: 'cust_471'
  }
];
